name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build
      run: make

    - name: Install Valgrind
      run: |
        if ! command -v valgrind &> /dev/null
        then
            sudo apt-get update
            sudo apt-get install valgrind
        fi
      
    - name: Build and run with Valgrind
      run: make valgrind
