name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build
      run: make

    - name: Cache Valgrind
      id: cache-valgrind
      uses: actions/cache@v3
      env:
        cache-name: cache-valgrind-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: valgrind

    - if: ${{ steps.cache-valgrind.outputs.cache-hit != 'true' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind

    - name: Build and run with Valgrind
      run: make valgrind
