name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build
      run: make
      
    - name: Install Valgrind
      run: sudo apt-get install valgrind
      
    - name: Build and run with Valgrind
      run: make valgrind
    - name: Build and run Unit Tests
      run: make test
