name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build
      run: make

    - name: Create Valgrind directory
      run: |
        sudo mkdir -p /usr/local/valgrind
        sudo chown -R $USER:$USER /usr/local/valgrind

    - name: Cache Valgrind
      id: cache-valgrind
      uses: actions/cache@v2
      with:
        path: /usr/local/valgrind
        key: valgrind
  
    - name: Install Valgrind
      if: steps.cache-valgrind.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind
        sudo cp -r /usr/lib/valgrind/* /usr/local/valgrind
        export PATH="/usr/local/valgrind/bin:$PATH"

    - name: Build and run with Valgrind
      run: make valgrind
