name: Valgrind Caching

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check file permissions
        run: ls -l /usr/bin/valgrind

      - name: Cache Valgrind
        id: cache-valgrind
        uses: actions/cache@v2
        with:
          path: /usr/bin/valgrind
          key: valgrind-${{ runner.os }}-${{ github.ref }}-$(md5sum /usr/bin/valgrind | awk '{print $1}')

      - name: Install Valgrind
        if: steps.cache-valgrind.outputs.cache-hit != 'true'
        run: sudo apt-get install -y valgrind
