name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check file permissions
        run: ls -l /usr/bin/valgrind

      - name: Cache Valgrind
        id: cache-valgrind
        uses: actions/cache@v2
        with:
          path: /usr/bin/valgrind
          key: valgrind-${{ runner.os }}-${{ github.ref }}-$(md5sum /usr/bin/valgrind | awk '{print $1}')

      - name: Install Valgrind
        if: steps.cache-valgrind.outputs.cache-hit != 'true'
        run: sudo apt-get install -y valgrind
=======
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build
      run: make
      
    - name: Install Valgrind
      run: sudo apt-get install valgrind
      
    - name: Build and run with Valgrind
      run: make valgrind
>>>>>>> edf0f91ff8cf8d439a57ebc8e26c39dc95871116
