name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build
      run: make

    - name: Cache Valgrind
      id: cache-valgrind
      uses: actions/cache@v2
      with:
        path: /usr/lib/valgrind
        key: valgrind

    - name: Install Valgrind
      if: steps.cache-valgrind.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install valgrind

      
    - name: Build and run with Valgrind
      run: make valgrind
